name: project_tpm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  basic_utils: ^5.7.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_polyline_points: ^2.1.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  rsa_encrypt: ^2.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/
